//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pex.rc
//
#define ID_DELETE                       3
#define IDD_ABOUTBOX                    100
#define IDB_LIGHTBULB                   102
#define IDD_TIP                         103
#define CG_IDS_TIPOFTHEDAY              104
#define CG_IDS_TIPOFTHEDAYMENU          105
#define CG_IDS_DIDYOUKNOW               106
#define IDD_GENERAL                     106
#define CG_IDS_FILE_ABSENT              107
#define CG_IDP_FILE_CORRUPT             108
#define CG_IDS_TIPOFTHEDAYHELP          109
#define IDR_MAINFRAME                   128
#define IDR_PEX32TYPE                   129
#define IDS_PROPTITLE                   129
#define IDR_TMOBIL                      130
#define IDS_APPENDFILE                  130
#define IDR_TELMI                       131
#define IDR_QUIX                        132
#define IDD_TX                          133
#define IDR_UNKNOWN                     135
#define IDD_DECODER                     136
#define IDD_SPLASH                      137
#define IDD_ENCODER                     138
#define IDB_TLOGO                       138
#define IDD_HARDWARE                    140
#define IDR_OWNMSG                      142
#define IDR_LEVELBAR                    161
#define IDD_LICENSE                     163
#define IDB_EYES                        164
#define IDB_TLOGO_I                     170
#define IDR_CONTEXT                     170
#define IDD_STATISTIC                   171
#define IDD_FILTER                      178
#define IDD_LISTMANAGER                 180
#define IDD_ENTRYPROPERTIES             181
#define IDD_REGISTER                    185
#define IDD_MYMESSAGEBOX                186
#define IDC_PORT                        1000
#define IDC_BULB                        1000
#define IDC_INT                         1001
#define IDC_STARTUP                     1001
#define IDC_PASSWORD                    1001
#define IDC_MSG                         1002
#define IDC_NEXTTIP                     1002
#define IDC_COMBO_BITRATE               1003
#define IDC_TIPSTRING                   1004
#define IDC_ENCODE                      1006
#define IDC_FCT                         1007
#define IDC_BITRATE                     1008
#define IDC_TXINV                       1009
#define IDC_ADR                         1009
#define IDC_PTTINV                      1011
#define IDC_FCT0                        1013
#define IDC_FILTER                      1015
#define IDC_DEBUG                       1016
#define IDC_FILTERFCT                   1016
#define IDC_FCT1                        1017
#define IDC_VERSION                     1017
#define IDC_FCT2                        1018
#define IDC_EDTTXDELAY                  1019
#define IDC_FCT3                        1019
#define IDC_SPNTXDELAY                  1020
#define IDC_DEBUG2                      1020
#define IDC_RXLINE                      1022
#define IDC_SYNCWORD                    1023
#define IDC_SOUNDCARD                   1024
#define IDC_USESNDCRD                   1025
#define IDC_USECOM                      1026
#define IDC_FIRFLT                      1027
#define IDC_CORR                        1028
#define IDC_CHANNELS                    1032
#define IDC_LICENSE                     1041
#define IDC_MSGNUM                      1049
#define IDC_MSGERR                      1050
#define IDC_EXBUFERR                    1051
#define IDC_DECRATE                     1052
#define IDC_SKYPER                      1052
#define IDC_CUTVISLISTNUM               1052
#define IDC_PROGRAMNAME                 1052
#define IDC_ALIAS                       1052
#define IDC_CHARSET                     1053
#define IDC_CHOOSEPROGRAM               1053
#define IDC_CUTINTERNALISTNUM           1053
#define IDC_PROGRAMNAME2                1053
#define IDC_TOTOP                       1054
#define IDC_CUTVISLIST                  1054
#define IDC_CUTINTERNALIST              1055
#define ID_LOADFILTER                   1055
#define IDC_SPIN1                       1056
#define IDC_STARTPRG                    1056
#define IDC_SPIN2                       1057
#define ID_SAVEFILTER                   1057
#define IDC_AUTOSAVE                    1058
#define IDC_AUTOSAVENUM                 1059
#define IDC_SPIN3                       1060
#define IDC_LOADLASTLIST                1061
#define IDC_ELIMINATECALLS              1062
#define IDC_ADDRESS                     1063
#define IDC_AUTOSCROLL                  1063
#define IDC_TIMESPAN                    1067
#define IDC_TCPIP                       1068
#define ID_CHOOSE                       1068
#define IDC_EDIT1                       1069
#define IDC_CODE                        1070
#define IDC_REGISTERED                  1070
#define IDC_NAME                        1071
#define ID_TX                           32771
#define ID_TMOBIL                       32773
#define ID_TELMI                        32776
#define ID_QUIX                         32777
#define ID_SETTINGS                     32780
#define ID_DCD                          32782
#define ID_1200                         32783
#define ID_2400                         32784
#define ID_512                          32785
#define ID_FIND                         32786
#define ID_AUTOBAUD                     32787
#define ID_AUTOMSG                      32790
#define ID_STOP                         32793
#define ID_LEVEL                        32797
#define ID_LEVEL_VIEW                   32803
#define ID_AOT                          32805
#define ID_SKYPER                       32806
#define ID_HIDE                         32807
#define ID_CHOOSEFONT                   32809
#define ID_GOWWW                        32811
#define ID_FEEDBACK                     32812
#define ID_LICENSE                      32813
#define ID_OPTIONS_PROPERTIES           32814
#define ID_OPTIONS_FLEX_PROPERTIES      32815
#define ID_EUROPOINT                    32816
#define ID_ENTRYPROPERTIES              32817
#define IDS_DELETECMD                   32818
#define ID_REGISTER                     32819
#define ID_DELETECMD                    32820
#define ID_UPDATEALL                    32821
#define IDS_NUMBER                      33446
#define IDS_TIME                        33447
#define IDS_TYPE                        33448
#define IDS_BITRATE                     33449
#define IDS_ADDRESS                     33450
#define IDS_FUNC                        33451
#define IDS_MSG                         33452
#define IDS_NOMATCHES                   33453
#define IDS_NOCLIPBRD                   33454
#define IDS_NOCLPCPY                    33455
#define IDS_MONPRT                      33456
#define IDS_MONPRTFILE                  33457
#define IDS_MONPRTPAGE                  33458
#define IDS_PORTERR                     33459
#define IDS_NOVXD                       33460
#define IDS_WRONGVXD                    33461
#define IDS_STORING                     33462
#define IDS_LOADING                     33463
#define IDS_UPDLIST                     33464
#define IDS_FLTACT                      33465
#define IDS_NOSEL                       33466
#define IDS_NOITEMS                     33467
#define IDS_FMTERR                      33468
#define IDS_SYNCERR                     33469
#define IDS_SOURCE                      33470
#define IDS_WAVERR                      33471
#define IDS_WAITSND                     33472
#define IDS_DORX                        33473
#define ID_TESTID                       33474
#define ID_LEVEL0                       33475
#define ID_LEVEL1                       33476
#define IDS_LICSTR1                     33477
#define IDS_LICSTR2                     33478
#define IDS_WNDTOP                      33479
#define IDS_NOFILE                      33480
#define IDS_TBLFILE                     33481
#define IDS_NODEFASSOC                  33482
#define IDS_PROPTITLEGENERAL            33483
#define IDS_ALIAS                       33484
#define IDS_MSGCNT                      33485
#define IDS_UPTIME                      33486
#define IDS_UPTIME_DAY                  33487
#define IDS_UPTIME_DAYS                 33488
#define IDS_MSGS                        33489
#define IDS_DELETE                      33490
#define IDS_LISTEN_INUSE                33491
#define IDS_LISTEN_ERROR                33492
#define IDS_CANT_LISTEN                 33493
#define IDS_REGISTERED                  33494

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
